oauth2:
  kakao:
    grant-type: authorization_code
    client-id: b49d403eab459f2dcb5d7b635c14139b
    redirect-url: https://localhost:3000/oauth2/kakao
    base-url: https://kauth.kakao.com/oauth/token
    user-info-url: https://kapi.kakao.com/v2/user/me

jwt:
  secret-key: 7JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri4Cg==
  access-expiration-sec: 1800
  refresh-expiration-sec: 25184000
