spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/werow?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: giri
    password: 9463

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    com.werow: ${VIEW_DEBUG:debug}

jwt:
  header: Authorization
  secret: 7JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri47JWI7JiB6ri4Cg==
  token-validate-sec: 86400