spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: 277902945783-9atqkqg7v43kvd54ijrg0phrct39j5tc.apps.googleusercontent.com
            client_secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          kakao:
            client-id: e485731066d013c1fc6faaf79bfc6d04
            redirect-url: http://localhost:8080/api/login/kakao
            base-url: https://kauth.kakao.com/oauth/token
            grant-type: authorization_code
            user-info-url: https://kapi.kakao.com/v2/user/me
#        provider:
